;配置文件
[Common]
;调试信息开关
debug_level = 2
;日志目录
debug_path = /tmp/log
;日志保存时间(单位: 天)
log_savetime = 7
;监控与bmc通信端口
log_bmcport = 16000
;心跳超时时间
heartbeat_timeout = 5
;心跳重置次数
heartbeat_reset_times = -1
;上电失败复位次数
poweron_reset_times = 10
;启动超时使能
start_timeout_enable = 1
;开机启动超时时间，单位秒
start_timeout = 300
;cpu数量
cpu_num = 1
;单板类型,1-lc,2-fab,3-dpc
board_type = 1



